<a href="https://colab.research.google.com/github/EighteenSprings/BaiduPaperReproduction2end/blob/main/DeblurGANv2_instancenorm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install paddlepaddle
!pip install x2paddle

     |████████████████████████████████| 108.8MB 74kB/s 
     |████████████████████████████████| 296kB 5.3MB/s 


In [ ]:
!pip install gdown

In [ ]:
import os
from gdown import download as drive_download

def gdownloader(gdrive_url, save_path, gdrive_filename):
    try:
        if not os.path.exists(save_path):
            os.mkdir(save_path)
        file_path = os.path.join(save_path,gdrive_filename)
        drive_download(gdrive_url, file_path, quiet=False)
        print("Done!")
    except Exception:
        print('Error')

In [ ]:
pretrained_model = {
    "InceptionResNet-v2":{
        "url": "https://drive.google.com/uc?id=1UXcsRVW-6KF23_TNzxw-xC0SzaMfXOaR",
        "filename":"fpn_inception.h5"
    }
}
InceptionResNetV2 = pretrained_model['InceptionResNet-v2']

In [ ]:
gdownloader(InceptionResNetV2["url"], "model", InceptionResNetV2["filename"])

Downloading...
From: https://drive.google.com/uc?id=1UXcsRVW-6KF23_TNzxw-xC0SzaMfXOaR
To: /content/model/fpn_inception.h5
244MB [00:02, 102MB/s]


Done!


In [ ]:
import torch
import paddle

In [ ]:
model_state_dict = torch.load('model/fpn_inception.h5', map_location=torch.device('cpu'))

In [ ]:
model_state_dict['model'].keys()

odict_keys(['module.fpn.inception.conv2d_1a.conv.weight', 'module.fpn.inception.conv2d_1a.bn.weight', 'module.fpn.inception.conv2d_1a.bn.bias', 'module.fpn.inception.conv2d_1a.bn.running_mean', 'module.fpn.inception.conv2d_1a.bn.running_var', 'module.fpn.inception.conv2d_1a.bn.num_batches_tracked', 'module.fpn.inception.conv2d_2a.conv.weight', 'module.fpn.inception.conv2d_2a.bn.weight', 'module.fpn.inception.conv2d_2a.bn.bias', 'module.fpn.inception.conv2d_2a.bn.running_mean', 'module.fpn.inception.conv2d_2a.bn.running_var', 'module.fpn.inception.conv2d_2a.bn.num_batches_tracked', 'module.fpn.inception.conv2d_2b.conv.weight', 'module.fpn.inception.conv2d_2b.bn.weight', 'module.fpn.inception.conv2d_2b.bn.bias', 'module.fpn.inception.conv2d_2b.bn.running_mean', 'module.fpn.inception.conv2d_2b.bn.running_var', 'module.fpn.inception.conv2d_2b.bn.num_batches_tracked', 'module.fpn.inception.conv2d_3b.conv.weight', 'module.fpn.inception.conv2d_3b.bn.weight', 'module.fpn.inception.conv2d_3b.bn

In [ ]:
!wget -P model http://data.lip6.fr/cadene/pretrainedmodels/inceptionresnetv2-520b38e4.pth

HTTP request sent, awaiting response... 200 OK
Length: 223774246 (213M) [application/octet-stream]
Saving to: ‘model/inceptionresnetv2-520b38e4.pth’

inceptionresnetv2-5 100%[===================>] 213.41M   362KB/s    in 10m 29s 

2021-05-29 17:03:57 (347 KB/s) - ‘model/inceptionresnetv2-520b38e4.pth’ saved [223774246/223774246]



In [ ]:
inceptionresnetv2_t = torch.load("model/inceptionresnetv2-520b38e4.pth")

In [ ]:
inceptionresnetv2_t.keys()

dict_keys(['repeat.8.branch2.0.conv.weight', 'repeat_1.18.branch1.1.bn.running_mean', 'repeat_1.12.branch1.1.bn.weight', 'repeat_1.4.conv2d.weight', 'repeat_1.14.branch1.0.bn.running_var', 'repeat_1.17.branch1.1.bn.weight', 'repeat.5.branch1.0.bn.weight', 'conv2d_1a.bn.running_var', 'repeat_2.6.branch1.0.bn.bias', 'repeat.4.branch1.0.bn.running_mean', 'repeat_2.4.branch0.bn.running_var', 'repeat.9.branch2.0.bn.bias', 'block8.branch1.1.bn.bias', 'repeat_1.2.branch1.0.conv.weight', 'repeat.6.branch2.1.bn.bias', 'repeat.8.branch2.0.bn.running_mean', 'repeat_1.11.branch1.0.conv.weight', 'repeat.7.branch2.2.conv.weight', 'repeat_1.11.branch1.2.bn.running_mean', 'repeat_2.6.branch1.2.conv.weight', 'repeat_2.7.branch0.bn.running_var', 'repeat_1.18.branch1.2.bn.bias', 'repeat_1.13.branch1.0.bn.running_var', 'repeat_1.14.branch1.1.conv.weight', 'repeat_1.10.branch0.bn.bias', 'repeat.3.branch0.bn.running_var', 'last_linear.weight', 'repeat_2.3.branch1.2.bn.weight', 'mixed_6a.branch1.1.bn.running

In [ ]:
!wget https://raw.githubusercontent.com/Cadene/pretrained-models.pytorch/master/pretrainedmodels/models/inceptionresnetv2.py

--2021-05-29 17:16:50--  https://raw.githubusercontent.com/Cadene/pretrained-models.pytorch/master/pretrainedmodels/models/inceptionresnetv2.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12055 (12K) [text/plain]
Saving to: ‘inceptionresnetv2.py’

inceptionresnetv2.p 100%[===================>]  11.77K  --.-KB/s    in 0s      

2021-05-29 17:16:50 (80.3 MB/s) - ‘inceptionresnetv2.py’ saved [12055/12055]



In [ ]:
!rm inceptionresnetv2_t.py
!cp inceptionresnetv2.py inceptionresnetv2_t.py

In [16]:
import inceptionresnetv2_t as ipt_t
import inceptionresnetv2_p as ipt_p

In [17]:
model_t = ipt_t.InceptionResNetV2(num_classes=1001)
model_p = ipt_p.InceptionResNetV2(num_classes=1001)

In [18]:
model_p_dk = model_p.state_dict()
model_t_dk = model_t.state_dict()

In [62]:
len(model_p_dk.keys()),len(model_t_dk.keys())

(1102, 1306)

In [ ]:
len(inceptionresnetv2_t.keys())

1102

In [ ]:
len([x for x in model_t_dk.keys() if x.endswith("num_batches_tracked")])

204

In [ ]:
for i, (k_p, k_t) in enumerate(zip(model_p_dk.keys(), [x for x in model_t_dk.keys() if not x.endswith("num_batches_tracked")])):
  print(i, k_p, '=====', k_t)

0 conv2d_1a.conv.weight ===== conv2d_1a.conv.weight
1 conv2d_1a.bn.weight ===== conv2d_1a.bn.weight
2 conv2d_1a.bn.bias ===== conv2d_1a.bn.bias
3 conv2d_1a.bn._mean ===== conv2d_1a.bn.running_mean
4 conv2d_1a.bn._variance ===== conv2d_1a.bn.running_var
5 conv2d_2a.conv.weight ===== conv2d_2a.conv.weight
6 conv2d_2a.bn.weight ===== conv2d_2a.bn.weight
7 conv2d_2a.bn.bias ===== conv2d_2a.bn.bias
8 conv2d_2a.bn._mean ===== conv2d_2a.bn.running_mean
9 conv2d_2a.bn._variance ===== conv2d_2a.bn.running_var
10 conv2d_2b.conv.weight ===== conv2d_2b.conv.weight
11 conv2d_2b.bn.weight ===== conv2d_2b.bn.weight
12 conv2d_2b.bn.bias ===== conv2d_2b.bn.bias
13 conv2d_2b.bn._mean ===== conv2d_2b.bn.running_mean
14 conv2d_2b.bn._variance ===== conv2d_2b.bn.running_var
15 conv2d_3b.conv.weight ===== conv2d_3b.conv.weight
16 conv2d_3b.bn.weight ===== conv2d_3b.bn.weight
17 conv2d_3b.bn.bias ===== conv2d_3b.bn.bias
18 conv2d_3b.bn._mean ===== conv2d_3b.bn.running_mean
19 conv2d_3b.bn._variance ===== con

In [ ]:
all([True for x in list(inceptionresnetv2_t.keys()) if x in list(model_p_dk.keys())])

True

In [14]:
%cd /content/work
import paddle
import torch
from collections import OrderedDict
import pickle

/content/work


In [22]:
inceptionresnetv2_t = torch.load('/content/model/inceptionresnetv2-520b38e4.pth')
paddle_new_dict = OrderedDict()
for paddle_key,torch_key in zip(model_p_dk.keys(), [x for x in model_t_dk.keys() if not x.endswith("num_batches_tracked")]):
  if 'linear' in paddle_key.split('.')[-2]:
    print(paddle_key)
    paddle_new_dict[paddle_key] = inceptionresnetv2_t[torch_key].detach().numpy().T
  else:
    paddle_new_dict[paddle_key] = inceptionresnetv2_t[torch_key].detach().numpy()
with open('inceptionresnetv2_p.pdparams', 'wb') as f:
  pickle.dump(paddle_new_dict, f)

last_linear.weight
last_linear.bias


In [66]:
model_p.load_dict(paddle.load('inceptionresnetv2_p.pdparams'))

/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py:1297: UserWarning: Skip loading for last_linear.weight. last_linear.weight receives a shape [1001, 1536], but the expected shape is [1536, 1001].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))


In [ ]:
!cp inceptionresnetv2_p.pdparams /content/drive/MyDrive/GAN/DeblurGANv2

## instancenorm2d

In [ ]:
import paddle.nn as nn
from paddle.nn.functional import instance_norm

class InstanceNorm2d(nn.Layer):
    """
    This class is based class for InstanceNorm1D, 2d, 3d. 
    See InstaceNorm1D, InstanceNorm2D or InstanceNorm3D for more details.
    """

    def __init__(self,
                 num_features,
                 epsilon=1e-5,
                 momentum=0.9,
                 weight_attr=None,
                 bias_attr=None,
                 data_format="NCHW",
                 name=None):
        super(_InstanceNormBase, self).__init__()

        if weight_attr == False or bias_attr == False:
            assert weight_attr == bias_attr, "weight_attr and bias_attr must be set to Fasle at the same time in InstanceNorm"
        self._epsilon = epsilon
        self._weight_attr = weight_attr
        self._bias_attr = bias_attr

        if weight_attr != False and bias_attr != False:
            self.scale = self.create_parameter(
                attr=self._weight_attr,
                shape=[num_features],
                default_initializer=Constant(1.0),
                is_bias=False)
            self.bias = self.create_parameter(
                attr=self._bias_attr,
                shape=[num_features],
                default_initializer=Constant(0.0),
                is_bias=True)
        else:
            self.scale = None
            self.bias = None

    def _check_input_dim(self, input):
        if len(input.shape) != 4:
            raise ValueError('expected 4D input (got {}D input)'.format(
                len(input.shape)))

    def forward(self, input):
        self._check_input_dim(input)

        return instance_norm(
            input, weight=self.scale, bias=self.bias, eps=self._epsilon)

    def extra_repr(self):
        return 'num_features={}, epsilon={}'.format(self.scale.shape[0],
                                                    self._epsilon)

In [ ]:
in_t = torch.nn.InstanceNorm2d(100, affine=True)
in_p = paddle.nn.InstanceNorm2D(num_features=100, weight_attr=True, bias_attr=True)

In [ ]:
import numpy as np

In [ ]:
x = np.random.rand(1, 100, 64, 64).astype(np.float32)
x_t = torch.from_numpy(x)
x_p = paddle.to_tensor(x)

In [ ]:
np.testing.assert_allclose(in_t(x_t).detach().cpu().numpy(), in_p(x_p).detach().cpu().numpy())

AssertionError: ignored

In [ ]:
import paddle

def get_norm_layer(norm_type='instance'):
    if norm_type == 'batch':
        norm_layer = functools.partial(nn.BatchNorm2d, weight_attr=True, bias_attr=True)
    elif norm_type == 'instance':
        norm_layer = functools.partial(nn.InstanceNorm2d, weight_attr=True, bias_attr=True)
    else:
        raise NotImplementedError('normalization layer [%s] is not found' % norm_type)
    return norm_layer

In [9]:
!rm -rf model

In [5]:
%cd /content/
!zip -q -r /content/drive/MyDrive/Work/DeblurGANv2/work.zip work
!zip -q -r /content/drive/MyDrive/Work/DeblurGANv2/model.zip model
%cd work

/content
/content/work


In [ ]:
!rm -rf model
!rm -rf work

In [7]:
!unzip -q /content/drive/MyDrive/Work/DeblurGANv2/work.zip -d .
!unzip -q /content/drive/MyDrive/Work/DeblurGANv2/model.zip -d .

replace ./model/inceptionresnetv2-520b38e4.pth? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [30]:
%cd work

/content/work


In [2]:
import yaml

with open('config/config.yaml') as cfg:
  config = yaml.load(cfg)
config['model']

{'adv_lambda': 0.001,
 'blocks': 9,
 'content_loss': 'perceptual',
 'd_layers': 3,
 'd_name': 'double_gan',
 'disc_loss': 'wgan-gp',
 'dropout': True,
 'g_name': 'fpn_inception',
 'learn_residual': True,
 'norm_layer': 'instance'}

In [3]:
import networks_t

In [4]:
model_g_t  = networks_t.get_generator(config['model'])

In [14]:
"model_g_t.state_dict().keys()",len(model_g_t.state_dict().keys()), len([x for x in model_g_t.state_dict().keys() if not x.endswith("num_batches_tracked")])

('model_g_t.state_dict().keys()', 2384, 2012)

In [15]:
# 查看 fpn_inception.h5 的参数个数
import torch
test_state_dict = torch.load('/content/model/fpn_inception.h5', map_location=torch.device('cpu'))
len(test_state_dict['model'].keys())

2384

In [8]:
import paddle
import paddle.nn as nn_p
import torch
import torch.nn as nn_t
import numpy as np

In [9]:
linear_p = nn_p.Linear(10,10)
linear_t = nn_t.Linear(10,10)

In [10]:
linear_new_weight = np.random.rand(11,10).astype(np.float32)
linear_new_weight

array([[8.5512459e-01, 5.3082687e-01, 5.2483964e-01, 8.9949971e-01,
        6.1144072e-01, 3.8811275e-01, 8.1796050e-02, 7.2327965e-01,
        7.7235883e-01, 3.8134196e-01],
       [7.7083552e-01, 4.9762115e-01, 5.5177402e-01, 5.4581022e-01,
        4.0651923e-01, 1.8649544e-01, 9.1570210e-01, 2.5547025e-01,
        3.1251225e-01, 9.8989749e-01],
       [8.8155830e-01, 2.7977133e-01, 2.0344328e-04, 6.3892311e-01,
        5.9131092e-01, 9.2678839e-01, 6.1577076e-01, 4.4377980e-01,
        7.0901519e-01, 3.9665792e-02],
       [5.6734103e-01, 4.2180173e-02, 7.4561834e-02, 9.9308068e-01,
        7.8669512e-01, 4.4965786e-01, 3.7048614e-01, 6.4385548e-02,
        7.6378536e-01, 4.7061631e-01],
       [3.3337212e-01, 7.2621578e-01, 7.7218187e-01, 2.4432026e-01,
        7.5970553e-02, 8.1041753e-01, 7.0987952e-01, 1.0477323e-01,
        4.0745598e-01, 5.0558209e-01],
       [7.8205550e-01, 6.0065895e-01, 4.1503242e-01, 5.1162577e-01,
        7.4334514e-01, 9.1027343e-01, 4.9262075e-03, 3.31

In [53]:
linear_t.weight.data = torch.from_numpy(linear_new_weight)[1:]
linear_t.weight

Parameter containing:
tensor([[0.4390, 0.3377, 0.0030, 0.0750, 0.0490, 0.6924, 0.9764, 0.3239, 0.3102,
         0.2118],
        [0.6468, 0.2991, 0.3512, 0.5673, 0.6531, 0.1530, 0.5342, 0.7890, 0.7472,
         0.2963],
        [0.6367, 0.0660, 0.9835, 0.4253, 0.6254, 0.2897, 0.7320, 0.5047, 0.4688,
         0.1789],
        [0.4267, 0.2899, 0.0614, 0.6353, 0.4762, 0.0595, 0.9079, 0.7272, 0.1672,
         0.7134],
        [0.8137, 0.3864, 0.6391, 0.7269, 0.3521, 0.8082, 0.9775, 0.3082, 0.7832,
         0.2601],
        [0.3860, 0.0030, 0.2418, 0.9646, 0.2094, 0.1445, 0.4926, 0.1037, 0.0490,
         0.0088],
        [0.5697, 0.5996, 0.1817, 0.8138, 0.4863, 0.5082, 0.1343, 0.8007, 0.9933,
         0.0919],
        [0.8496, 0.3147, 0.2539, 0.1151, 0.6330, 0.4250, 0.2064, 0.8443, 0.4356,
         0.9012],
        [0.3371, 0.8247, 0.7086, 0.3851, 0.8644, 0.6908, 0.7703, 0.4699, 0.7032,
         0.3461],
        [0.9620, 0.9896, 0.8388, 0.8159, 0.4043, 0.6342, 0.1705, 0.1927, 0.4812,
      

In [16]:
linear_p.weight.set_value(linear_new_weight[1:])
linear_p.weight.value
new_linear = nn_p.Linear(10,10)
new_linear.weight.set_value(linear_p.weight.detach().numpy())

In [51]:
linear_p.weight[1:]

Tensor(shape=[9, 10], dtype=float32, place=CPUPlace, stop_gradient=False,
       [[0.45556971, 0.72864884, 0.10700054, 0.53075236, 0.38853502, 0.43445241, 0.02289046, 0.65532029, 0.63694680, 0.96094841],
        [0.58223438, 0.37954718, 0.81510454, 0.07726010, 0.05803346, 0.97192162, 0.83371413, 0.60419321, 0.81852549, 0.49954459],
        [0.87253374, 0.32882243, 0.07931733, 0.23797603, 0.09358963, 0.01136917, 0.07168984, 0.13035800, 0.36521974, 0.91496587],
        [0.74177688, 0.91973114, 0.61551613, 0.23708586, 0.89372337, 0.07686203, 0.72259486, 0.78461677, 0.02755834, 0.28321281],
        [0.84633249, 0.68299544, 0.60528421, 0.07787077, 0.72284168, 0.93835050, 0.30477268, 0.82818097, 0.29684347, 0.40448311],
        [0.55562991, 0.26155818, 0.50775343, 0.85548437, 0.97107881, 0.44355512, 0.21002963, 0.80586708, 0.06853718, 0.45385495],
        [0.37879086, 0.89960837, 0.91659665, 0.92257351, 0.74896032, 0.66155422, 0.98174530, 0.33560520, 0.86870915, 0.98172510],
        [0.91686

In [1]:
%cd /content/work
import inceptionresnetv2_p as ipt_p

/content/work


In [2]:
model_test = ipt_p.inceptionresnetv2(num_classes=1000, pretrained='imagenet')

出错原因：FC 层权重需要转置

In [5]:
import torch
import paddle
import torch.nn as nn_t
import paddle.nn as nn_p

In [6]:
fc_t = nn_t.Linear(3,5)
fc_p = nn_p.Linear(3,5)

In [9]:
print(f"PyTorch Weight Shape: {fc_t.weight.shape}, PyTorch Bias Shape: {fc_t.bias.shape}")
print(f"Paddle Weight Shape: {fc_p.weight.shape}, Paddle Bias Shape: {fc_p.bias.shape}")

PyTorch Weight Shape: torch.Size([5, 3]), PyTorch Bias Shape: torch.Size([5])
Paddle Weight Shape: [3, 5], Paddle Bias Shape: [5]


测试 inceptionresnetv2 转换的如何

In [1]:
%cd work
import paddle
import torch
import numpy as np
import inceptionresnetv2_p as ipt_p
import inceptionresnetv2_t as ipt_t

/content/work


In [2]:
torch_model = ipt_t.inceptionresnetv2(num_classes=1000, pretrained='imagenet')
paddle_model = ipt_p.inceptionresnetv2(num_classes=1000, pretrained='imagenet')

In [3]:
x = np.random.rand(1,3,299, 299).astype(np.float32)
x_t = torch.from_numpy(x)
x_p = paddle.to_tensor(x)

In [4]:
out_t = torch_model(x_t)
out_p = paddle_model(x_p)
np.testing.assert_allclose(out_t.detach().numpy(), out_p.detach().numpy())

/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")


AssertionError: ignored

In [5]:
print(f"out_t {out_t.shape}, out_p {out_p.shape}")

out_t torch.Size([1, 1000]), out_p [1, 1000]


# 保存环境

In [145]:
%cd /content/
!zip -q -r /content/drive/MyDrive/Work/DeblurGANv2/work.zip work
!zip -q -r /content/drive/MyDrive/Work/DeblurGANv2/model.zip model
%cd work

/content
/content/work


# 恢复环境

In [1]:
%cd /content
!unzip -q /content/drive/MyDrive/Work/DeblurGANv2/work.zip -d .
!unzip -q /content/drive/MyDrive/Work/DeblurGANv2/model.zip -d .
%cd /work

/content
[Errno 2] No such file or directory: '/work'
/content


## fpn_inceptin

In [1]:
%cd /content/work

/content/work


In [2]:
import yaml
import networks_t as net_t
import networks_p as net_p

In [19]:
with open('config/config.yaml', 'r') as f:
  config = yaml.load(f)

gent_t = net_t.get_generator(config['model'])

In [13]:
len(gent_t.state_dict().keys())

2384

In [7]:
layer_p = net_p.get_norm_layer('instance')
layer_t = net_t.get_norm_layer('instance')

In [7]:
import fpn_inception_p as fpn_p
import fpn_inception_t as fpn_t

In [8]:
model_p = fpn_p.FPN(norm_layer=net_p.get_norm_layer(norm_type='instance'))
model_t = fpn_t.FPN(norm_layer=net_t.get_norm_layer(norm_type='instance'))

In [14]:
print(f"FPN_p {len(model_p.state_dict().keys())} , FPN_t {len([x for x in model_t.state_dict().keys() if not x.endswith('num_batches_tracked')])}")

FPN_p 1988 , FPN_t 1994


In [16]:
for i,(paddle_key, torch_key) in enumerate(zip(list(model_p.state_dict().keys())[-994:], [x for x in model_t.state_dict().keys() if not x.endswith('num_batches_tracked')][-994:])):
  print(i, paddle_key, '====', torch_key)

0 inception.repeat_2.5.branch1.0.bn._variance ==== inception.repeat_2.5.branch1.2.conv.weight
1 inception.repeat_2.5.branch1.1.conv.weight ==== inception.repeat_2.5.branch1.2.bn.weight
2 inception.repeat_2.5.branch1.1.bn.weight ==== inception.repeat_2.5.branch1.2.bn.bias
3 inception.repeat_2.5.branch1.1.bn.bias ==== inception.repeat_2.5.branch1.2.bn.running_mean
4 inception.repeat_2.5.branch1.1.bn._mean ==== inception.repeat_2.5.branch1.2.bn.running_var
5 inception.repeat_2.5.branch1.1.bn._variance ==== inception.repeat_2.5.conv2d.weight
6 inception.repeat_2.5.branch1.2.conv.weight ==== inception.repeat_2.5.conv2d.bias
7 inception.repeat_2.5.branch1.2.bn.weight ==== inception.repeat_2.6.branch0.conv.weight
8 inception.repeat_2.5.branch1.2.bn.bias ==== inception.repeat_2.6.branch0.bn.weight
9 inception.repeat_2.5.branch1.2.bn._mean ==== inception.repeat_2.6.branch0.bn.bias
10 inception.repeat_2.5.branch1.2.bn._variance ==== inception.repeat_2.6.branch0.bn.running_mean
11 inception.repea

In [20]:
[x for x in model_t.state_dict().keys() if not x.endswith('num_batches_tracked')][-17:]

['td1.0.weight',
 'td1.0.bias',
 'td1.1.running_mean',
 'td1.1.running_var',
 'td2.0.weight',
 'td2.0.bias',
 'td2.1.running_mean',
 'td2.1.running_var',
 'td3.0.weight',
 'td3.0.bias',
 'td3.1.running_mean',
 'td3.1.running_var',
 'lateral4.weight',
 'lateral3.weight',
 'lateral2.weight',
 'lateral1.weight',
 'lateral0.weight']

In [21]:
list(model_p.state_dict().keys())[-11:]

['td1.0.weight',
 'td1.0.bias',
 'td2.0.weight',
 'td2.0.bias',
 'td3.0.weight',
 'td3.0.bias',
 'lateral4.weight',
 'lateral3.weight',
 'lateral2.weight',
 'lateral1.weight',
 'lateral0.weight']

In [22]:
import torch

In [40]:
fpn_inception = torch.load('/content/model/fpn_inception.h5', map_location=torch.device('cpu'))
len(fpn_inception['model'].keys())

2384

In [41]:
layer_test = torch.nn.InstanceNorm2d(num_features=100, affine=False, track_running_stats=True)

In [44]:
layer_out = layer_test(torch.rand((1,100, 64, 64)))

In [46]:
layer_test.state_dict().keys()

odict_keys(['running_mean', 'running_var', 'num_batches_tracked'])

In [85]:
import paddle
import functools
def get_norm_layer(norm_type='instance'):
    if norm_type == 'batch':
        norm_layer = functools.partial(paddle.nn.BatchNorm2D)
    elif norm_type == 'instance':
        norm_layer = functools.partial(paddle.nn.InstanceNorm2D, weight_attr=paddle.ParamAttr(trainable=False), bias_attr=paddle.ParamAttr(trainable=False))
    else:
        raise NotImplementedError('normalization layer [%s] is not found' % norm_type)
    return norm_layer

In [81]:
norm_layer_p = get_norm_layer(norm_type='instance')
layer_p = norm_layer_p(num_features=100)

In [82]:
layer_p_out = layer_p(paddle.rand(shape=(1,100,64,64)))

In [83]:
layer_p.state_dict().keys()

odict_keys(['scale', 'bias'])

In [84]:
layer_p.state_dict()['scale']

Parameter containing:
Tensor(shape=[100], dtype=float32, place=CPUPlace, stop_gradient=False,
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
list(fpn_inception['model'].keys())[-50:]

['module.fpn.enc4.1.branch2.1.bn.bias',
 'module.fpn.enc4.1.branch2.1.bn.running_mean',
 'module.fpn.enc4.1.branch2.1.bn.running_var',
 'module.fpn.enc4.1.branch2.1.bn.num_batches_tracked',
 'module.fpn.enc4.1.branch2.2.conv.weight',
 'module.fpn.enc4.1.branch2.2.bn.weight',
 'module.fpn.enc4.1.branch2.2.bn.bias',
 'module.fpn.enc4.1.branch2.2.bn.running_mean',
 'module.fpn.enc4.1.branch2.2.bn.running_var',
 'module.fpn.enc4.1.branch2.2.bn.num_batches_tracked',
 'module.fpn.td1.0.weight',
 'module.fpn.td1.0.bias',
 'module.fpn.td1.1.running_mean',
 'module.fpn.td1.1.running_var',
 'module.fpn.td1.1.num_batches_tracked',
 'module.fpn.td2.0.weight',
 'module.fpn.td2.0.bias',
 'module.fpn.td2.1.running_mean',
 'module.fpn.td2.1.running_var',
 'module.fpn.td2.1.num_batches_tracked',
 'module.fpn.td3.0.weight',
 'module.fpn.td3.0.bias',
 'module.fpn.td3.1.running_mean',
 'module.fpn.td3.1.running_var',
 'module.fpn.td3.1.num_batches_tracked',
 'module.fpn.lateral4.weight',
 'module.fpn.late

In [72]:
fpn_inception['model']['module.fpn.td1.1.running_mean']

tensor([ 212.7692,  -68.1490,  -60.7377,  -65.7689,  -70.4767, -251.4737,
           3.1155,  273.9222,   29.9879,  -24.7812,  204.8107,   91.3336,
         185.9740, -307.4042,  -68.1102,  -24.7952,  156.0201,   59.2417,
         -51.6598,  -22.6001,   -0.9784,   35.4206,   55.6639,  160.3168,
          96.7116,  148.0283,  130.7430,   10.3951,  -74.8521,   60.4304,
        -141.5410, -205.8552,  313.3047,   60.4536, -274.1172, -169.8297,
         -49.4560,  220.3649, -332.8842,   44.8910,   29.4535,   23.0892,
         -11.0239,   18.6415,   -2.3297,   62.3678,  -34.0494,   33.0166,
          44.1105,  225.4011,   12.4063, -191.6653,   75.1009, -128.5061,
        -170.4174,   -7.4304,  265.0609,   16.6714, -251.7509,  112.1579,
         -57.4047, -196.8652,   53.9888, -198.9196,  -96.9022,   22.3713,
        -122.5747, -549.9575,   99.3022, -312.2927, -128.1343,  132.6674,
          14.8627, -364.9331,    9.0475,   36.0429,  136.3789, -166.3029,
         -63.6754,   -9.5659,   85.985

对比 InstanceNorm2d

In [90]:
# paddle example
import paddle
import numpy as np

np.random.seed(123)
x_data = np.random.random(size=(2, 2, 2, 3)).astype('float32')
x = paddle.to_tensor(x_data)
instance_norm = paddle.nn.InstanceNorm2D(2)
instance_norm_out = instance_norm(x)

print(instance_norm_out)
print(instance_norm.state_dict()['bias'])

Tensor(shape=[2, 2, 2, 3], dtype=float32, place=CPUPlace, stop_gradient=False,
       [[[[ 1.12517858, -1.04670870, -1.36052132],
          [ 0.35687223,  1.24691701, -0.32173795]],

         [[ 1.71713412,  0.37617615, -0.54773909],
          [-0.95018065, -1.17193866,  0.57654858]]],


        [[[ 0.47514182, -1.21473753,  0.29438582],
          [ 1.81057727, -0.66698438, -0.69838291]],

         [[-1.03305471, -1.03058565, -0.11365463],
          [ 1.80856359,  0.69136512, -0.32263216]]]])
Parameter containing:
Tensor(shape=[2], dtype=float32, place=CPUPlace, stop_gradient=False,
       [0., 0.])


In [94]:
import paddle
import numpy as np

x = np.random.seed(123)
x = np.random.random(size=(2, 1, 2, 3)).astype('float32')
running_mean = np.random.random(size=1).astype('float32')
running_variance = np.random.random(size=1).astype('float32')
weight_data = np.random.random(size=1).astype('float32')
bias_data = np.random.random(size=1).astype('float32')
x = paddle.to_tensor(x)
rm = paddle.to_tensor(running_mean)
rv = paddle.to_tensor(running_variance)
w = paddle.to_tensor(weight_data)
b = paddle.to_tensor(bias_data)
print(f"running_mean {running_mean}")

instance_norm_out = paddle.nn.functional.instance_norm(x, rm, rv, w, b)
print(instance_norm_out)

print(f"running_mean {running_mean}")

running_mean [0.43857226]
Tensor(shape=[2, 1, 2, 3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[[[1.18586624, 0.32135901, 0.19644767],
          [0.88004631, 1.23432350, 0.60992944]]],


        [[[1.42149079, 0.88773012, 0.51997101],
          [0.35978144, 0.27151194, 0.96748722]]]])
running_mean [0.43857226]


In [97]:
[x for x in dir(paddle.nn.Layer) if 'load' in x]

['load_dict']

In [4]:
import paddle.nn as nn
def build_norm_layer(norm_type='instance'):
    """Return a normalization layer
    Args:
        norm_type (str) -- the name of the normalization layer: batch | instance | none
    For BatchNorm, we use learnable affine parameters and track running statistics (mean/stddev).
    For InstanceNorm, we do not use learnable affine parameters. We do not track running statistics.
    """
    if norm_type == 'batch':
        norm_layer = functools.partial(
            nn.BatchNorm,
            param_attr=paddle.ParamAttr(
                initializer=nn.initializer.Normal(1.0, 0.02)),
            bias_attr=paddle.ParamAttr(
                initializer=nn.initializer.Constant(0.0)),
            trainable_statistics=True)
    elif norm_type == 'instance':
        norm_layer = functools.partial(
            nn.InstanceNorm2D,
            weight_attr=paddle.ParamAttr(
                initializer=nn.initializer.Constant(1.0),
                learning_rate=0.0,
                trainable=False),
            bias_attr=paddle.ParamAttr(initializer=nn.initializer.Constant(0.0),
                                       learning_rate=0.0,
                                       trainable=False))
    elif norm_type == 'spectral':
        norm_layer = functools.partial(Spectralnorm)
    elif norm_type == 'none':

        def norm_layer(x):
            return Identity()
    else:
        raise NotImplementedError('normalization layer [%s] is not found' %
                                  norm_type)
    return norm_layer

In [112]:
weight_attr=paddle.ParamAttr(
                initializer=nn.initializer.Constant(1.0),
                learning_rate=0.1,
                trainable=True)

In [115]:
param_shape = [10]
weight = paddle.create_parameter(
                attr=None,
                shape=param_shape,
                dtype='float32'
            )

In [124]:
import numpy as np
import paddle

linear = paddle.nn.Linear(10, 3)
value = np.array([0]).astype("float32")
buffer = paddle.to_tensor(value)
linear.register_buffer("buf_name", buffer, persistable=True)

print(list(linear.named_buffers()))     # == print([linear.buf_name])

[('buf_name', Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=True,
       [0.]))]


In [125]:
class TestLayer(paddle.nn.Layer):
  def __init__(self):
    super(TestLayer, self).__init__()
  
  def forward(self, x):
    return x_data

In [127]:
[x for x in dir(TestLayer) if 'dict' in x]

['__dict__', 'load_dict', 'set_dict', 'set_state_dict', 'state_dict']

In [184]:

import paddle
import paddle.nn as nn
from paddle.nn.initializer import Constant
from paddle.nn.functional import instance_norm

class InstanceNorm2d(paddle.nn.Layer):

    def __init__(
        self,
        num_features: int,
        eps: float = 1e-5,
        momentum: float = 0.1,
        affine: bool = False,
        name: str = None
        ):
        super(InstanceNorm2d, self).__init__()
        self._eps = eps
        self._momentum = momentum
        param_shape = [num_features]
        self.affine = affine
        if affine:
            self.weight = self.create_parameter(
                attr=None,
                shape=param_shape,
                default_initializer=Constant(1.0)
            )
            self.bias = self.create_parameter(
                attr=None,
                shape=param_shape,
                default_initializer=Constant(0.0)
            )
        else:
            weight_attr=paddle.ParamAttr(
                initializer=nn.initializer.Constant(1.0),
                learning_rate=0.0,
                trainable=False)
            bias_attr=paddle.ParamAttr(initializer=nn.initializer.Constant(0.0),
                                       learning_rate=0.0,
                                       trainable=False)
            self.weight = self.create_parameter(
                attr=weight_attr,
                shape=param_shape
            )
            self.bias = self.create_parameter(
                attr=bias_attr,
                shape=param_shape,
                is_bias=True
            )
        
        moving_mean_name = None
        moving_variance_name = None

        if name is not None:
            moving_mean_name = name + "_mean"
            moving_variance_name = name + "_variance"

        self._mean = self.create_parameter(
            attr=paddle.ParamAttr(
                name=moving_mean_name,
                initializer=Constant(1.0),
                trainable=False,
                do_model_average=True),
            shape=param_shape)
        self._mean.stop_gradient = True

        self._variance = self.create_parameter(
            attr=paddle.ParamAttr(
                name=moving_variance_name,
                initializer=Constant(1.0),
                trainable=False,
                do_model_average=True),
            shape=param_shape)
        self._variance.stop_gradient = True
        
    def forward(self, x):
        return instance_norm(
            x, 
            running_mean=self._mean, 
            running_var=self._variance, 
            weight=self.weight, 
            bias=self.bias, 
            use_input_stats=self.training,
            eps=self._eps,
            momentum=self._momentum
            )

In [10]:
import numpy as np
x = np.random.rand(4,10,4,4).astype(np.float32)

In [11]:
x.mean(axis=)

((4, 4), array([[0.25630546, 0.280481  , 0.29520106, 0.28208062],
        [0.27791032, 0.2983065 , 0.28423184, 0.23604757],
        [0.28366786, 0.26648667, 0.2860931 , 0.30827108],
        [0.278542  , 0.3089684 , 0.2631116 , 0.24402562]], dtype=float32))

In [185]:
in_p = InstanceNorm2d(10)
in_p.eval()
in_p(paddle.to_tensor(x))

Tensor(shape=[1, 10, 4, 4], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[[[-1.24177420, -1.27351499,  0.33201683,  0.33326215],
          [ 0.79573065,  1.76523149,  1.20175493,  0.69032955],
          [ 1.19268405, -0.60845548, -0.43338537, -1.03540611],
          [-0.74031061,  0.78028929, -1.64929736, -0.10915628]],

         [[-0.39307401, -0.14483465, -0.41295946, -0.86172199],
          [-0.41090074,  1.43457592,  1.63519454, -0.11262418],
          [ 0.36991215, -1.63874626, -0.84186894, -0.45644158],
          [ 1.32757068, -1.10594475, -0.18692093,  1.79878342]],

         [[-0.20275812,  0.30091441, -2.35343027,  1.45183706],
          [ 0.24788633, -0.06481262, -1.15565610, -1.36402321],
          [-0.75524795,  0.66976732,  1.71667564, -0.25162542],
          [ 0.60513240,  0.15555434,  0.36566788,  0.63411635]],

         [[ 1.33226287, -1.24808550,  1.06489825, -0.70264196],
          [-0.87070054,  0.41491991, -1.20553839,  1.47836709],
          [ 0.60115

In [166]:
import paddle.nn as nn

In [182]:
in_p2 = nn.InstanceNorm2D(10)
in_p2(paddle.to_tensor(x))

Tensor(shape=[1, 10, 4, 4], dtype=float32, place=CPUPlace, stop_gradient=False,
       [[[[-1.24177420, -1.27351499,  0.33201683,  0.33326215],
          [ 0.79573065,  1.76523149,  1.20175493,  0.69032955],
          [ 1.19268405, -0.60845548, -0.43338537, -1.03540611],
          [-0.74031061,  0.78028929, -1.64929736, -0.10915628]],

         [[-0.39307401, -0.14483465, -0.41295946, -0.86172199],
          [-0.41090074,  1.43457592,  1.63519454, -0.11262418],
          [ 0.36991215, -1.63874626, -0.84186894, -0.45644158],
          [ 1.32757068, -1.10594475, -0.18692093,  1.79878342]],

         [[-0.20275812,  0.30091441, -2.35343027,  1.45183706],
          [ 0.24788633, -0.06481262, -1.15565610, -1.36402321],
          [-0.75524795,  0.66976732,  1.71667564, -0.25162542],
          [ 0.60513240,  0.15555434,  0.36566788,  0.63411635]],

         [[ 1.33226287, -1.24808550,  1.06489825, -0.70264196],
          [-0.87070054,  0.41491991, -1.20553839,  1.47836709],
          [ 0.6011

In [177]:
in_p._variance

Parameter containing:
Tensor(shape=[10], dtype=float32, place=CPUPlace, stop_gradient=True,
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [178]:
paddle.mean(paddle.to_tensor(x), axis=1)

Tensor(shape=[1, 4, 4], dtype=float32, place=CPUPlace, stop_gradient=True,
       [[[0.43187529, 0.51981777, 0.50141799, 0.34934250],
         [0.57669151, 0.74101245, 0.40596113, 0.52530801],
         [0.53883588, 0.41957569, 0.52821571, 0.45548740],
         [0.61159885, 0.57635659, 0.50543869, 0.55377680]]])

# InstanceNorm 实现

In [13]:
import torch
import torch.nn as nn_t
import paddle
import paddle.nn as nn_p
import numpy as np

In [58]:
x = np.random.rand(4,3,4,4).astype(np.float32)
inputs = [np.random.randn(4,3,4,4).astype(np.float32) for _ in range(10)]
inputs_mean = np.mean(inputs, axis=0)
inputs_std = np.std(inputs,axis=0)
print(inputs_mean.shape, inputs_std.shape)

(4, 3, 4, 4) (4, 3, 4, 4)


## PyTorch 的属性

In [118]:
# torch
model_t = nn_t.InstanceNorm2d(num_features=3, affine=False, track_running_stats=True)
model_t.train()
for i,x in enumerate(inputs):
  x_t = torch.from_numpy(x)
  print(f"running_mean: {model_t.state_dict()['running_mean']}, running_var {model_t.state_dict()['running_var']}")
  model_t(x_t)
print(model_t.state_dict())

running_mean: tensor([0., 0., 0.]), running_var tensor([1., 1., 1.])
running_mean: tensor([-0.0010, -0.0055, -0.0018]), running_var tensor([1.0221, 0.9898, 1.0002])
running_mean: tensor([-0.0069,  0.0078,  0.0248]), running_var tensor([1.0345, 0.9866, 1.0115])
running_mean: tensor([-0.0021, -0.0295, -0.0007]), running_var tensor([1.0270, 0.9649, 0.9928])
running_mean: tensor([ 0.0008, -0.0288,  0.0161]), running_var tensor([1.0654, 0.9704, 1.0018])
running_mean: tensor([ 0.0253, -0.0235,  0.0239]), running_var tensor([1.0547, 1.0091, 0.9844])
running_mean: tensor([ 0.0239, -0.0215,  0.0135]), running_var tensor([1.0771, 1.0298, 0.9946])
running_mean: tensor([ 0.0235, -0.0007,  0.0309]), running_var tensor([1.0619, 1.0369, 1.0056])
running_mean: tensor([0.0118, 0.0051, 0.0221]), running_var tensor([1.0359, 1.0207, 0.9769])
running_mean: tensor([0.0288, 0.0186, 0.0033]), running_var tensor([1.0362, 0.9949, 0.9780])
OrderedDict([('running_mean', tensor([0.0106, 0.0192, 0.0127])), ('runnin

In [114]:
# 查看属性
model_t.state_dict()

OrderedDict([('running_mean', tensor([0.0106, 0.0192, 0.0127])),
             ('running_var', tensor([1.0379, 0.9822, 0.9697])),
             ('num_batches_tracked', tensor(0))])

In [125]:
# 用 numpy 实现带有 momentum 的 求均值 方法
mean_old = np.zeros(shape=(4,3), dtype=np.float32)
var_old = np.ones(shape=(4,3),dtype=np.float32)
for x in inputs:
  print(np.mean(mean_old, axis=0))
  mean_new = 0.9*mean_old + 0.1*np.mean(x, axis=(2,3))
  var_new = 0.9*var_old + 0.1*np.var(x, axis=(2,3))
  mean_old = mean_new
  var_old = var_new
print(f'mean {mean_new.mean(axis=0)} var {var_new.mean(axis=0)}')

[0. 0. 0.]
[-0.00104981 -0.00550465 -0.00181595]
[-0.00690152  0.00780115  0.02477468]
[-0.00208528 -0.02948513 -0.00073425]
[ 0.00083726 -0.02878846  0.01613767]
[ 0.02526435 -0.02353404  0.02387664]
[ 0.02393323 -0.02146449  0.0134816 ]
[ 0.02351987 -0.0006884   0.0308891 ]
[0.01177469 0.00512802 0.02214941]
[0.02876797 0.01857697 0.00333672]
mean [0.01064607 0.0191895  0.01269662] var [0.9948067  0.94257224 0.9308446 ]


In [127]:
# 用 torch 实现
mean_old = torch.zeros(4,3, dtype=torch.float32)
var_old = torch.ones(4,3,dtype=torch.float32)
for x in inputs:
  x_t = torch.from_numpy(x)
  print(f"running_mean {torch.mean(mean_old,dim=0)} running_var {torch.mean(var_old, dim=0)}")
  mean_new = 0.9*mean_old+0.1*torch.mean(x_t, dim=(2,3))
  var_new = 0.9*var_old+0.1*torch.var(x_t, dim=(2,3))
  mean_old = mean_new
  var_old = var_new
print(f"running_mean {torch.mean(mean_old,dim=0)} running_var {torch.mean(var_old, dim=0)}")


running_mean tensor([0., 0., 0.]) running_var tensor([1., 1., 1.])
running_mean tensor([-0.0010, -0.0055, -0.0018]) running_var tensor([1.0221, 0.9898, 1.0002])
running_mean tensor([-0.0069,  0.0078,  0.0248]) running_var tensor([1.0345, 0.9866, 1.0115])
running_mean tensor([-0.0021, -0.0295, -0.0007]) running_var tensor([1.0270, 0.9649, 0.9928])
running_mean tensor([ 0.0008, -0.0288,  0.0161]) running_var tensor([1.0654, 0.9704, 1.0018])
running_mean tensor([ 0.0253, -0.0235,  0.0239]) running_var tensor([1.0547, 1.0091, 0.9844])
running_mean tensor([ 0.0239, -0.0215,  0.0135]) running_var tensor([1.0771, 1.0298, 0.9946])
running_mean tensor([ 0.0235, -0.0007,  0.0309]) running_var tensor([1.0619, 1.0369, 1.0056])
running_mean tensor([0.0118, 0.0051, 0.0221]) running_var tensor([1.0359, 1.0207, 0.9769])
running_mean tensor([0.0288, 0.0186, 0.0033]) running_var tensor([1.0362, 0.9949, 0.9780])
running_mean tensor([0.0106, 0.0192, 0.0127]) running_var tensor([1.0379, 0.9822, 0.9697])


可以看到结果一模一样  
我的结果
```python
running_mean tensor([0.0106, 0.0192, 0.0127]) running_var tensor([1.0379, 0.9822, 0.9697])
```
torch 的结果
```python
OrderedDict([('running_mean', tensor([0.0106, 0.0192, 0.0127])), ('running_var', tensor([1.0379, 0.9822, 0.9697])), ('num_batches_tracked', tensor(0))])
```

## Paddle 的属性

In [26]:
model_p = nn_p.InstanceNorm2D(
    num_features=3, 
    weight_attr=paddle.ParamAttr(
        initializer=paddle.nn.initializer.Constant(0.0),
        learning_rate=0.0,
        trainable=False
    ),
    bias_attr=paddle.ParamAttr(
        initializer=paddle.nn.initializer.Constant(1.0),
        learning_rate=0.0,
        trainable=False
    )
    )
model_p.train()
for x in inputs:
  x_p = paddle.to_tensor(x)
  model_p(x_p)

In [27]:
model_p.state_dict()

OrderedDict([('scale', Parameter containing:
              Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
                     [0., 0., 0.])), ('bias', Parameter containing:
              Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
                     [1., 1., 1.]))])

对比两个结果

In [72]:
eval_x = np.random.rand(1,3,4,4).astype(np.float32)
model_p.eval()
eval_x_out_p = model_p(paddle.to_tensor(eval_x))
model_t.eval()
eval_x_out_t = model_t(torch.from_numpy(eval_x))
np.testing.assert_allclose(eval_x_out_p.detach().numpy(), eval_x_out_t.detach().numpy())

AssertionError: ignored

由以上结果可以看出，paddle 的 InstanceNorm2D 并没有实现完全，没有办法保存均值和方差

## 实现 InstanceNorm2d 相关功能

先用 paddle 实现简单的 instancenorm

In [4]:
import torch
import torch.nn as nn_t
import paddle
import paddle.nn as nn_p
import numpy as np

In [5]:
inputs = [np.random.randn(4,3,4,4).astype(np.float32) for _ in range(10)]

In [6]:
# torch
model_t = nn_t.InstanceNorm2d(num_features=3, affine=False, track_running_stats=True)
model_t.train()
for i,x in enumerate(inputs):
  x_t = torch.from_numpy(x)
  print(f"running_mean: {model_t.state_dict()['running_mean']}, running_var {model_t.state_dict()['running_var']}")
  instancenorm_out_t = model_t(x_t)
print(f"running_mean: {model_t.state_dict()['running_mean']}, running_var {model_t.state_dict()['running_var']}")

running_mean: tensor([0., 0., 0.]), running_var tensor([1., 1., 1.])
running_mean: tensor([ 0.0231, -0.0096, -0.0081]), running_var tensor([1.0027, 0.9739, 0.9879])
running_mean: tensor([ 0.0205, -0.0059, -0.0176]), running_var tensor([1.0159, 0.9556, 0.9695])
running_mean: tensor([ 0.0064, -0.0122, -0.0300]), running_var tensor([1.0305, 0.9474, 0.9912])
running_mean: tensor([-0.0012, -0.0073, -0.0273]), running_var tensor([1.0026, 0.9481, 0.9953])
running_mean: tensor([-0.0009, -0.0064,  0.0014]), running_var tensor([0.9931, 0.9282, 0.9788])
running_mean: tensor([-0.0097, -0.0115,  0.0062]), running_var tensor([0.9750, 0.9279, 0.9848])
running_mean: tensor([-0.0052,  0.0019, -0.0128]), running_var tensor([0.9840, 0.9314, 0.9730])
running_mean: tensor([-0.0068,  0.0057, -0.0165]), running_var tensor([0.9872, 0.9585, 0.9858])
running_mean: tensor([-0.0043,  0.0199, -0.0197]), running_var tensor([1.0041, 0.9830, 0.9776])
running_mean: tensor([-0.0114,  0.0133, -0.0112]), running_var tens

In [9]:
# paddle
mean_old = paddle.zeros(shape=(4,3), dtype=paddle.float32)
var_old = paddle.ones(shape=(4,3), dtype=paddle.float32)
for x in inputs:
  x_p = paddle.to_tensor(x)
  print(f"running_mean: {paddle.mean(mean_old, axis=0).numpy()}, running_var {paddle.mean(var_old, axis=0).numpy()}")
  mean_new = 0.9*mean_old + 0.1*paddle.mean(x_p, axis=(2,3), keepdim=False)
  var_new = 0.9*var_old + 0.1*paddle.var(x_p, axis=(2,3), keepdim=False)
  mean_old = mean_new
  var_old = var_new
print(f"running_mean: {paddle.mean(mean_old, axis=0).numpy()}, running_var {paddle.mean(var_old, axis=0).numpy()}")
instancenorm_out_p = nn_p.functional.instance_norm(paddle.to_tensor(inputs[-1]), running_mean=paddle.mean(mean_old,axis=0), running_var=paddle.mean(var_old,axis=0), momentum=0.1)

running_mean: [0. 0. 0.], running_var [1. 1. 1.]
running_mean: [ 0.02310152 -0.00960292 -0.00805376], running_var [1.0027357 0.9739235 0.9878799]
running_mean: [ 0.02053952 -0.00588624 -0.017583  ], running_var [1.0158958  0.95564514 0.96946573]
running_mean: [ 0.00639815 -0.01217436 -0.0300415 ], running_var [1.0304803  0.94742614 0.99120504]
running_mean: [-0.00119413 -0.00727308 -0.02728056], running_var [1.0026276 0.9481054 0.9952858]
running_mean: [-0.00094633 -0.0064243   0.00143052], running_var [0.99306726 0.9282237  0.97875845]
running_mean: [-0.00974739 -0.01152828  0.00615666], running_var [0.9749814  0.92790675 0.9848041 ]
running_mean: [-0.00515873  0.00185458 -0.01282581], running_var [0.98395586 0.9313953  0.97301984]
running_mean: [-0.00679985  0.0057012  -0.01651479], running_var [0.98721784 0.9584533  0.98581433]
running_mean: [-0.00429371  0.01987794 -0.01973053], running_var [1.0040889  0.98303807 0.9775926 ]
running_mean: [-0.01135335  0.01332354 -0.01122218], runn

In [8]:
np.testing.assert_allclose(instancenorm_out_p.numpy(), instancenorm_out_t.numpy())

AssertionError: ignored

可以看出来两种实现基本结果是一样的

In [14]:
import paddle
from paddle import ParamAttr
from paddle.nn.initializer import Constant

class MyInstanceNorm(paddle.nn.Layer):
  def __init__(self, num_features, momentum=0.1, eps=1e-5):
    super(MyInstanceNorm,self).__init__()
    param_shape = [num_features]
    self._momentum = momentum
    self._eps = eps
    self._mean = paddle.zeros(shape=param_shape, dtype=paddle.float32, name='_mean')
    self._variance = paddle.ones(shape=param_shape, dtype=paddle.float32, name='_variance')
  
  def forward(self, x):
    self._mean = (1-self._momentum)*self._mean+self._momentum*paddle.mean(paddle.mean(x, axis=(2,3)), axis=0)
    self._variance = (1-self._momentum)*self._variance+self._momentum*paddle.mean(paddle.var(x, axis=(2,3)), axis=0)
    return paddle.nn.functional.instance_norm(x, running_mean=self._mean, running_var=self._variance, momentum=self._momentum, eps=self._eps)

In [15]:
my_model = MyInstanceNorm(3)
for x in inputs:
  x_p = paddle.to_tensor(x)
  my_out = my_model(x_p)

In [18]:
print(my_model._mean, my_model._variance)

Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [-0.01135335,  0.01332354, -0.01122218]) Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [1.00503337, 1.02705753, 0.98302186])


In [19]:
print(my_model.state_dict())

OrderedDict()


可以看到结果的一致，但是 state_dict 并不会保存下来

In [46]:
# 测试 self.create_parameter
import paddle
from paddle import ParamAttr
from paddle.nn.initializer import Constant

class MyInstanceNorm2(paddle.nn.Layer):
  def __init__(self, num_features, momentum=0.1, eps=1e-5):
    super(MyInstanceNorm2,self).__init__()
    param_shape = [num_features]
    self._momentum = momentum
    self._eps = eps
    # self._mean = paddle.zeros(shape=param_shape, dtype=paddle.float32, name='_mean')
    self._mean = self.create_parameter(
        shape=param_shape,
        attr=paddle.ParamAttr(initializer=Constant(0.0), learning_rate=0.0, trainable=False),
        dtype='float32'
    )
    # self._variance = paddle.ones(shape=param_shape, dtype=paddle.float32, name='_variance')
    self._variance = self.create_parameter(
        shape=param_shape,
        attr=paddle.ParamAttr(initializer=Constant(1.0), learning_rate=0.0, trainable=False),
        dtype='float32'
    )
  
  def forward(self, x):
    self._mean.set_value((1-self._momentum)*self._mean+self._momentum*paddle.mean(paddle.mean(x, axis=(2,3)), axis=0))
    self._variance.set_value((1-self._momentum)*self._variance+self._momentum*paddle.mean(paddle.var(x, axis=(2,3)), axis=0))
    return paddle.nn.functional.instance_norm(x, running_mean=self._mean, running_var=self._variance, momentum=self._momentum, eps=self._eps)

### Parameter 功能测试

In [27]:
# test Parameter
# 通过查询源码可以知道 Parameter 继承自 Variable
test_param = paddle.create_parameter(shape=[3], dtype='float32', attr=paddle.ParamAttr(
    initializer=Constant(0.0), learning_rate=0.0, trainable=False
))

In [38]:
[x for x in dir(test_param) if 'value' in x]

['_grad_value', 'set_value', 'value']

In [44]:
# 测试赋值
test_param.set_value(paddle.ones(shape=[3], dtype='float32'))
test_param

Parameter containing:
Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [1., 1., 1.])

In [51]:
# 支持乘法操作
test_param*0.1

Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
       [0.10000000, 0.10000000, 0.10000000])

### 最后测试

In [47]:

my_model2 = MyInstanceNorm2(3)
for x in inputs:
  x_p = paddle.to_tensor(x)
  my_out = my_model2(x_p)

In [48]:
my_model2.state_dict()

OrderedDict([('_mean', Parameter containing:
              Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
                     [-0.01135335,  0.01332354, -0.01122218])),
             ('_variance', Parameter containing:
              Tensor(shape=[3], dtype=float32, place=CPUPlace, stop_gradient=True,
                     [1.00503337, 1.02705753, 0.98302186]))])

不容易，InstanceNorm 相当于简单实现了，接下来做整合