<a href="https://colab.research.google.com/github/EighteenSprings/BaiduPaperReproduction2end/blob/main/ReflectionPad2d_CaseStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
pad = nn.ReflectionPad2d(1)
a = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))
print(a)
print(pad(a))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[ 5.,  4.,  5.,  6.,  7.,  6.],
          [ 1.,  0.,  1.,  2.,  3.,  2.],
          [ 5.,  4.,  5.,  6.,  7.,  6.],
          [ 9.,  8.,  9., 10., 11., 10.],
          [13., 12., 13., 14., 15., 14.],
          [ 9.,  8.,  9., 10., 11., 10.]]]])


In [3]:
a = torch.ones(1,1,3,3, requires_grad=True)

In [4]:
def printGrad(grad):
  print(grad)

In [5]:
b = pad(a)
b.register_hook(printGrad)

In [6]:
c = b.sum()
c.backward()

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [7]:
a.grad

tensor([[[[1., 3., 1.],
          [3., 9., 3.],
          [1., 3., 1.]]]])